language: java
jdk:
  - openjdk11

branches:
  only:
    - main
# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# main 브랜치에 PUSH 되었을때 수행되는 명령어
script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - yuseogi0218@gmail.com