language: java
jdk:
  - openjdk11

# CI 실행시킬 브랜치
branches:
  only:
    - main
# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# main 브랜치에 PUSH 되었을때 수행되는 명령어
script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-webservice *
  - mkdir -p deploy
  - mv springboot-webservice.zip deploy/springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-webservice-deploy-s3
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: yuseogi0218/spring-webservice-deploy
      branch: main

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-webservice-deploy-s3
    key: springboot-webservice.zip
    bundle_type: zip
    application: springboot-webservice
    application_group: springboot-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: yuseogi0218/spring-webservice-deploy
      branch: main

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - yuseogi0218@gmail.com